# Generated by Django 4.1 on 2022-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(related_name='recipe_categories', to='app.category'),
        ),
    ]
