# Generated by Django 4.1 on 2022-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_recipe_prep_time_alter_recipe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
